export const services = [
  {
    id: "svc-1",
    name: "Plumbing",
    description: "Fix leaks, pipe repairs, drain cleaning, and water heater installation",
    icon: "Droplets",
  },
  {
    id: "svc-2",
    name: "Electrical",
    description: "Wiring, outlet installation, circuit breaker repair, and lighting setup",
    icon: "Zap",
  },
  {
    id: "svc-3",
    name: "AC Repair",
    description: "Air conditioner servicing, refrigerant refill, and thermostat repair",
    icon: "Snowflake",
  },
  {
    id: "svc-4",
    name: "Appliance Repair",
    description: "Washing machine, refrigerator, dishwasher, and oven maintenance",
    icon: "Refrigerator",
  },
  {
    id: "svc-5",
    name: "Carpentry",
    description: "Furniture assembly, door repair, cabinet installation, and woodwork",
    icon: "Hammer",
  },
];

export const vendors = [
  {
    id: "v-1",
    name: "Rahul Sharma",
    service: "Plumbing",
    serviceId: "svc-1",
    rating: 4.8,
    reviews: 142,
    price: 350,
    currency: "INR",
    experience: "8 years",
    availability: "Mon-Sat, 9 AM - 6 PM",
    location: "Mumbai",
    image: null,
  },
  {
    id: "v-2",
    name: "Priya Patel",
    service: "Electrical",
    serviceId: "svc-2",
    rating: 4.9,
    reviews: 203,
    price: 400,
    currency: "INR",
    experience: "12 years",
    availability: "Mon-Fri, 8 AM - 5 PM",
    location: "Delhi",
    image: null,
  },
  {
    id: "v-3",
    name: "Amit Kumar",
    service: "AC Repair",
    serviceId: "svc-3",
    rating: 4.7,
    reviews: 98,
    price: 500,
    currency: "INR",
    experience: "6 years",
    availability: "Mon-Sun, 10 AM - 7 PM",
    location: "Bangalore",
    image: null,
  },
  {
    id: "v-4",
    name: "Sneha Reddy",
    service: "Plumbing",
    serviceId: "svc-1",
    rating: 4.6,
    reviews: 87,
    price: 300,
    currency: "INR",
    experience: "5 years",
    availability: "Tue-Sat, 9 AM - 5 PM",
    location: "Hyderabad",
    image: null,
  },
  {
    id: "v-5",
    name: "Vikram Singh",
    service: "Carpentry",
    serviceId: "svc-5",
    rating: 4.9,
    reviews: 176,
    price: 450,
    currency: "INR",
    experience: "15 years",
    availability: "Mon-Sat, 8 AM - 6 PM",
    location: "Jaipur",
    image: null,
  },
  {
    id: "v-6",
    name: "Deepa Nair",
    service: "Appliance Repair",
    serviceId: "svc-4",
    rating: 4.5,
    reviews: 64,
    price: 380,
    currency: "INR",
    experience: "7 years",
    availability: "Mon-Fri, 10 AM - 6 PM",
    location: "Chennai",
    image: null,
  },
  {
    id: "v-7",
    name: "Arjun Menon",
    service: "Electrical",
    serviceId: "svc-2",
    rating: 4.8,
    reviews: 131,
    price: 420,
    currency: "INR",
    experience: "10 years",
    availability: "Mon-Sat, 9 AM - 7 PM",
    location: "Kochi",
    image: null,
  },
  {
    id: "v-8",
    name: "Kavitha Iyer",
    service: "AC Repair",
    serviceId: "svc-3",
    rating: 4.7,
    reviews: 109,
    price: 480,
    currency: "INR",
    experience: "9 years",
    availability: "Mon-Sun, 9 AM - 8 PM",
    location: "Pune",
    image: null,
  },
];

export const userBookings = [
  {
    id: "bk-1",
    service: "Plumbing",
    vendorId: "v-1",
    vendorName: "Rahul Sharma",
    date: "2026-02-20",
    time: "10:00 AM",
    status: "Pending",
    price: 350,
    notes: "Kitchen sink is leaking",
    address: "123 Marine Drive, Mumbai",
  },
  {
    id: "bk-2",
    service: "Electrical",
    vendorId: "v-2",
    vendorName: "Priya Patel",
    date: "2026-02-18",
    time: "2:00 PM",
    status: "In Progress",
    price: 400,
    notes: "Need new outlet installed in bedroom",
    address: "45 Connaught Place, Delhi",
  },
  {
    id: "bk-3",
    service: "AC Repair",
    vendorId: "v-3",
    vendorName: "Amit Kumar",
    date: "2026-02-10",
    time: "11:00 AM",
    status: "Completed",
    price: 500,
    notes: "AC not cooling properly",
    address: "78 MG Road, Bangalore",
  },
  {
    id: "bk-4",
    service: "Carpentry",
    vendorId: "v-5",
    vendorName: "Vikram Singh",
    date: "2026-02-05",
    time: "9:00 AM",
    status: "Completed",
    price: 450,
    notes: "Wardrobe door hinge repair",
    address: "12 MI Road, Jaipur",
  },
  {
    id: "bk-5",
    service: "Plumbing",
    vendorId: "v-4",
    vendorName: "Sneha Reddy",
    date: "2026-02-22",
    time: "3:00 PM",
    status: "Pending",
    price: 300,
    notes: "Bathroom tap replacement",
    address: "56 Banjara Hills, Hyderabad",
  },
  {
    id: "bk-6",
    service: "Appliance Repair",
    vendorId: "v-6",
    vendorName: "Deepa Nair",
    date: "2026-01-28",
    time: "1:00 PM",
    status: "Cancelled",
    price: 380,
    notes: "Washing machine not spinning",
    address: "90 Anna Nagar, Chennai",
  },
];

export const vendorBookings = [
  {
    id: "vbk-1",
    customerName: "Ananya Gupta",
    service: "Plumbing",
    date: "2026-02-20",
    time: "10:00 AM",
    status: "Pending",
    price: 350,
    notes: "Kitchen sink leaking badly",
    address: "123 Marine Drive, Mumbai",
  },
  {
    id: "vbk-2",
    customerName: "Rohit Mehta",
    service: "Plumbing",
    date: "2026-02-19",
    time: "11:30 AM",
    status: "Accepted",
    price: 350,
    notes: "Water heater installation",
    address: "45 Colaba Causeway, Mumbai",
  },
  {
    id: "vbk-3",
    customerName: "Meera Joshi",
    service: "Plumbing",
    date: "2026-02-18",
    time: "2:00 PM",
    status: "In Progress",
    price: 350,
    notes: "Pipe burst in bathroom",
    address: "78 Bandra West, Mumbai",
  },
  {
    id: "vbk-4",
    customerName: "Suresh Krishnan",
    service: "Plumbing",
    date: "2026-02-15",
    time: "9:00 AM",
    status: "Completed",
    price: 350,
    notes: "Drain cleaning service",
    address: "12 Powai, Mumbai",
  },
  {
    id: "vbk-5",
    customerName: "Lakshmi Rao",
    service: "Plumbing",
    date: "2026-02-14",
    time: "4:00 PM",
    status: "Completed",
    price: 350,
    notes: "Toilet repair",
    address: "34 Andheri East, Mumbai",
  },
  {
    id: "vbk-6",
    customerName: "Kiran Das",
    service: "Plumbing",
    date: "2026-02-12",
    time: "10:00 AM",
    status: "Completed",
    price: 350,
    notes: "Faucet replacement",
    address: "56 Juhu, Mumbai",
  },
  {
    id: "vbk-7",
    customerName: "Nisha Verma",
    service: "Plumbing",
    date: "2026-02-21",
    time: "1:00 PM",
    status: "Pending",
    price: 350,
    notes: "Shower head replacement",
    address: "89 Dadar, Mumbai",
  },
];

export const earningsData = {
  monthly: [
    { month: "Sep", earnings: 12400 },
    { month: "Oct", earnings: 18200 },
    { month: "Nov", earnings: 15600 },
    { month: "Dec", earnings: 21000 },
    { month: "Jan", earnings: 19500 },
    { month: "Feb", earnings: 8750 },
  ],
  totalEarnings: 95450,
  monthlyEarnings: 8750,
  averageBookingValue: 350,
  totalBookings: 273,
};

export const analyticsData = {
  bookingsByStatus: [
    { status: "Completed", count: 186, fill: "var(--color-chart-1)" },
    { status: "In Progress", count: 23, fill: "var(--color-chart-2)" },
    { status: "Pending", count: 34, fill: "var(--color-chart-4)" },
    { status: "Cancelled", count: 30, fill: "var(--color-chart-5)" },
  ],
  revenueGrowth: [
    { month: "Sep", revenue: 12400 },
    { month: "Oct", revenue: 18200 },
    { month: "Nov", revenue: 15600 },
    { month: "Dec", revenue: 21000 },
    { month: "Jan", revenue: 19500 },
    { month: "Feb", revenue: 8750 },
  ],
  topServices: [
    { name: "Pipe Repair", bookings: 89, revenue: 31150 },
    { name: "Drain Cleaning", bookings: 67, revenue: 23450 },
    { name: "Water Heater", bookings: 54, revenue: 18900 },
    { name: "Faucet Install", bookings: 38, revenue: 13300 },
    { name: "Toilet Repair", bookings: 25, revenue: 8750 },
  ],
};

export const userProfile = {
  name: "Ananya Gupta",
  email: "ananya@example.com",
  phone: "+91 98765 43210",
  address: "123 Marine Drive, Colaba, Mumbai 400001",
};

export const vendorProfile = {
  name: "Rahul Sharma",
  email: "rahul@example.com",
  phone: "+91 99876 54321",
  address: "45 Linking Road, Bandra, Mumbai 400050",
  servicesOffered: ["Pipe Repair", "Drain Cleaning", "Water Heater Installation", "Faucet Replacement"],
  pricePerHour: 350,
  experience: "8 years",
  availability: "Mon-Sat, 9 AM - 6 PM",
};
